# Generated by Django 5.1.4 on 2024-12-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='docx_download_price',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Price for downloading resume as DOCX', max_digits=10),
            preserve_default=False,
        ),
    ]
